### ISSUE TITLE
亲喷，最好不要喷！

### ISSUE THREAD

**Issue by gudqs7** [docer-savior/open-doc-generator-idea-plugin#1]
认真的说，不是激将法，不是欲情故纵，不是那些有的没的。。。。
能写这种插件，说明我很懒，所以对于维护这种事，我也是很抵触的（啊，除非正好是是我的刚需~~~）

留个联系方式吧（囧）最好别找我啊~~~~
HotSpringCloud

**Comment by zhou-xia-ping** [comment]
请问大佬是怎么学习到开发插件的，我看了一下你的代码，感觉有点看不懂，望指教

**Comment by stupdit1t** [comment]
高手啊

**Comment by gudqs7** [comment]
高手个锤子哦

发自我的iPhone

**Comment by stupdit1t** [comment]
最新哪个仓库啊,继续更啊,

**Comment by gudqs7** [comment]
> 最新哪个仓库啊,继续更啊,

(⊙o⊙)…   不更新了, 没动力

**Comment by gudqs7** [comment]
> 请问大佬是怎么学习到开发插件的，我看了一下你的代码，感觉有点看不懂，望指教

@oncevan  就普通看文档, 还有就是别人的插件的代码...  基础好就不会这么觉得了...  英文文档我也看不懂.... 我总觉得那文档不是很详细....    
我认识一个 UP主, 为了一个功能, 去翻IDEA社区版源码....  还没了好久找到到....  不是很友好吧, 毕竟不是国内的

**Comment by stupdit1t** [comment]
> > 最新哪个仓库啊,继续更啊,
> 
> (⊙o⊙)… 不更新了, 没动力

好吧，我看你开源的版本和插件市场的版本不一样， 我尝试加了个功能，对RequestHeader和PathVarable 参数的识别。同时加了个截切为txt接口，方便聊天发送接口信息，比如：

接口：获取菜单列表
地址：GET: http://10.30.80.12:5398/system/menu/list
协议：application/x-www-form-urlencoded
参数说明：
 ids  Long[]  ids搜索  
 keyword  String  关键词  
 params  Map<String, Object>  范围参数  
 id  Long  菜单ID  
 menuName  String  菜单名称  
 parentName  String  父菜单名称  
 parentId  Long  父菜单ID  
 orderNum  String  显示顺序  
 path  String  路由地址  
 component  String  组件路径  
 isFrame  String  是否为外链（0是 1否）  
 menuType  String  类型（M目录 C菜单 F按钮）  
 visible  String  菜单状态:0显示,1隐藏  
 perms  String  权限字符串  
 icon  String  菜单图标  
 children  List<SysMenuQueryParams>  子菜单  
 remark  String  备注  

Postman请求示例：
ids[0]:{}
keyword:关键词
params.key:{}
id:0
menuName:菜单名称
parentName:父菜单名称
parentId:0
orderNum:显示顺序
path:路由地址
component:组件路径
isFrame:是否为外链（0是 1否）
menuType:类型（M目录 C菜单 F按钮）
visible:菜单状态:0显示,1隐藏
perms:权限字符串
icon:菜单图标
children[0]:{}
remark:备注

**Comment by gudqs7** [comment]
@stupdit1t 更新了....
