### ISSUE TITLE
mac idea 2021.1上带泛型的参数的通用返回结果无法正常解析?

### ISSUE THREAD

**Issue by masterpopy** [docer-savior/open-doc-generator-idea-plugin#3]
我用的mac idea 2021.1 生成接口文档后如果我的返回里带有泛型参数,给的结果是一堆莫名其妙的东西..
是哪里有问题?

**Comment by gudqs7** [comment]
> 我用的mac idea 2021.1 生成接口文档后如果我的返回里带有泛型参数,给的结果是一堆莫名其妙的东西.. 是哪里有问题?

@masterpopy 嗯, 麻烦提供下 demo, 我好复现下看看. 目前再复杂的泛型和嵌套, 理论都是支持的; 如果不支持, 那就是代码不够完善......

**Comment by masterpopy** [comment]
public class GenericResult<T> extends AbstractResult {
    private static final long serialVersionUID = 1L;
    public static final GenericResult<Void> SUCCESS = new GenericResult<Void>() {
        private static final long serialVersionUID = -3815215167127265311L;

        public void setSuccess(boolean success) {
        }

        public void setCode(String code) {
        }

        public void setMsg(String msg) {
        }

        public void setRetry(boolean retry) {
        }

        public void setArgs(Object[] args) {
        }

        public void setData(Void data) {
        }
    };
    private T data;
}

似乎是因为这个SUCCESS对象造成的.最后生成的api文档里会有近1w行的类似这种内容:
 "data": {
    "TYPE": {
      "ANNOTATION": 44,
      "ENUM": 66,
      "SYNTHETIC": 48,
      "cachedConstructor": {
        "ACCESS_PERMISSION": {
          "name": "翠埃沂秤嫡掷贡焊侗残"
        },
        "override": true,
        "reflectionFactory": {
          "initted": true,
          "reflectionFactoryAccessPerm": {},
          "langReflectAccess": {},
          "hasStaticInitializerMethod": {
            "ACCESS_PERMISSION": {},
            "override": true,
            "reflectionFactory": {},
            "securityCheckCache": {},
            "hasRealParameterData": false,
            "parameters": [
              {
....省略约1w行.

当然我是去不掉这个SUCCESS的.这是公司的框架.
我自己单独写了一个测试类测试一下不带这个SUCCESS的类的似乎没问题.

**Comment by masterpopy** [comment]
public class GenericResult<T> extends AbstractResult {
    private static final long serialVersionUID = 1L;
    public static final GenericResult<Void> SUCCESS = new GenericResult<Void>() {
        private static final long serialVersionUID = -3815215167127265311L;

        public void setSuccess(boolean success) {
        }

        public void setCode(String code) {
        }

        public void setMsg(String msg) {
        }

        public void setRetry(boolean retry) {
        }

        public void setArgs(Object[] args) {
        }

        public void setData(Void data) {
        }
    };
    private T data;
}

似乎是因为这个SUCCESS对象造成的.最后生成的api文档里会有近1w行的类似这种内容:
 "data": {
    "TYPE": {
      "ANNOTATION": 44,
      "ENUM": 66,
      "SYNTHETIC": 48,
      "cachedConstructor": {
        "ACCESS_PERMISSION": {
          "name": "翠埃沂秤嫡掷贡焊侗残"
        },
        "override": true,
        "reflectionFactory": {
          "initted": true,
          "reflectionFactoryAccessPerm": {},
          "langReflectAccess": {},
          "hasStaticInitializerMethod": {
            "ACCESS_PERMISSION": {},
            "override": true,
            "reflectionFactory": {},
            "securityCheckCache": {},
            "hasRealParameterData": false,
            "parameters": [
              {
....省略约1w行.

当然我是去不掉这个SUCCESS的.这是公司的框架.
我自己单独写了一个测试类测试一下不带这个SUCCESS的类的似乎没问题.

**Comment by masterpopy** [comment]
希望可以做一个功能可以过滤某些字段?

**Comment by gudqs7** [comment]
> 希望可以做一个功能可以过滤某些字段?

@masterpopy 有的, 添加注释即可! 如:
```java

/**
 * 新增一个用户
 * @param addUserRequest 用户信息
 * @return 操作是否成功
 * #hiddenResponse SUCCESS
 */
public ResultBean<Boolean> addUser(AddUserRequest addUserRequest) {
    // .....
}
```

ResultBean.java
```java
@Data
public class ResultBean<T> {
    
    private static final ResultBean SUCCESS = new ResultBean();
    
    private Integer code;

    private String msg;

    private T data;

    ........

}

```

你先试试啊... 针对这种情况, 我看看能不能改进下......

**Comment by gudqs7** [comment]
@masterpopy  另外, 使用 #hiddenRequest 可以过滤参数, 参数key以springMVC的规则为准, 比如 上段实例代码中, 我要过滤 `AddUserRequest` 中的某个字段, 只需要 `#hiddenRequest xxx` 即可, 而非 `addUserRequest.xxx` 这样多个参数名称作为前缀.

**Comment by gudqs7** [comment]
@masterpopy 最后提一句, 注释中的 `#` 可以替换为 `@` 之所以用 `#` 是因为 idea 针对 `@` 会有黄色警告... 不是每个人都会关闭警告, 所以两种都支持!

**Comment by gudqs7** [comment]
@masterpopy 我是说, 有没有可能, 你用的不是最新版..... 我好像没能复现你的情况......   也可能是你提供的代码太模糊了... 结构不够清晰...  可以的话, 提供清晰的结构给我, 不用真实代码, 你脱敏下你的代码, 结构是一样的就行

**Comment by masterpopy** [comment]
这个TYPE应该是来自于某些基本类型里的静态TYPE属性.

**Comment by masterpopy** [comment]
我多测试了一下添加 
#hiddenResponse data.TYPE
后生成的文档显示
| data     | **Void**    |   |   |
data的类型为Void,而我的泛型为一个对象. Void里有TYPE这个属性,所以导致了这个问题.
可能是idea的bug,我用的是插件是最新的,idea是2021.1 apple silicon版本

**Comment by gudqs7** [comment]
> 我多测试了一下添加 #hiddenResponse data.TYPE 后生成的文档显示 | data | **Void** | | | data的类型为Void,而我的泛型为一个对象. Void里有TYPE这个属性,所以导致了这个问题. 可能是idea的bug,我用的是插件是最新的,idea是2021.1 apple silicon版本

(⊙o⊙)…
问题解决了吗? 我刚发布了一个版本(还在审核中), 这个版本过滤了 transient 和static修饰的字段

压缩包提前发你吧

[docer-savior-plugin-2.0.2.zip](https://github.com/docer-savior/open-doc-generator-idea-plugin/files/8579806/docer-savior-plugin-2.0.2.zip)

**Comment by masterpopy** [comment]
用你的最新的压缩包解决问题了,谢谢支持
